name: Build LAME Win Mac

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_lame:
    strategy:
      matrix:
        include:
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    name: Build LAME on ${{ matrix.name }}
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Windows-specific setup
      - name: Set up MSYS2 (Windows)
        if: matrix.name == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-nasm
            base-devel
            git

      # Download and extract LAME source
      - name: Download and extract LAME source code
        run: |
          curl -LO https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
          tar -xzf lame-3.100.tar.gz

      # Remove deprecated symbol
      - name: Remove 'lame_init_old' symbol
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            sed -i '' '/lame_init_old/d' lame-3.100/include/libmp3lame.sym
          else
            sed -i '/lame_init_old/d' lame-3.100/include/libmp3lame.sym
          fi

      # Build and install LAME
      - name: Build and install LAME (Windows)
        if: matrix.name == 'Windows'
        shell: msys2 {0}
        run: |
          cd lame-3.100
          ./configure \
            --prefix=/mingw64 \
            --enable-nasm \
            --disable-shared \
            --enable-static \
            CFLAGS="-O3 -march=x86-64 -mtune=generic"
          make -j$(nproc)
          make install DESTDIR=$GITHUB_WORKSPACE/lame-install
          
      - name: Build and install LAME (macOS)
        if: matrix.name == 'macOS'
        run: |
          cd lame-3.100
          export CFLAGS="-arch x86_64 -arch arm64"
          export LDFLAGS="-arch x86_64 -arch arm64"
          ./configure --prefix=$HOME/lame-install
          make
          make install

      # Copy binary to output
      - name: Copy LAME binary to output
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mkdir -p output
            cp $GITHUB_WORKSPACE/lame-install/mingw64/bin/lame.exe ./output/
          else
            mkdir -p output
            cp $HOME/lame-install/bin/lame ./output/
          fi

      # Package executable
      - name: Package LAME executable
        run: |
          cd output
          zip -j ../LAME-${{ matrix.name }}.zip *

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LAME-${{ matrix.name }}.zip
          path: LAME-${{ matrix.name }}.zip