name: Build LAME Win Mac

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_lame:
    strategy:
      matrix:
        include:
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    name: Build LAME on ${{ matrix.name }}
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install MSYS2 (Windows only)
      - name: Set up MSYS2
        if: matrix.name == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-iconv
            mingw-w64-x86_64-ncurses
            mingw-w64-x86_64-gettext

      - name: Download and extract LAME source code
        run: |
          curl -LO https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
          tar -xzf lame-3.100.tar.gz

      # Remove lame_init_old symbol (this is still needed for both platforms)
      - name: Remove deprecated symbol
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            sed -i '' '/lame_init_old/d' lame-3.100/include/libmp3lame.sym
          else
            sed -i '/lame_init_old/d' lame-3.100/include/libmp3lame.sym
          fi

      # Build LAME (Windows)
      - name: Build LAME (Windows)
        if: matrix.name == 'Windows'
        shell: msys2 {0}
        run: |
          cd lame-3.100
          ./configure --prefix=$HOME/lame-install
          make
          make install

      # Build LAME (macOS)
      - name: Build LAME (macOS)
        if: matrix.name == 'macOS'
        run: |
          cd lame-3.100
          export CFLAGS="-arch x86_64 -arch arm64"
          export LDFLAGS="-arch x86_64 -arch arm64"
          ./configure --prefix=$HOME/lame-install
          make
          make install

      - name: Copy LAME binary to output
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cp $HOME/lame-install/bin/lame.exe ./lame
          else
            cp $HOME/lame-install/bin/lame ./lame
          fi

      - name: Package LAME executable
        run: |
          zip -j LAME-${{ matrix.name }}.zip lame

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LAME-${{ matrix.name }}.zip
          path: LAME-${{ matrix.name }}.zip