#  ___                 _        _                ___ ___ 
# | _ \__ _ _ __  _ __| |___ _ | |_  _ __ ___   / __|_ _|
# |  _/ _` | '  \| '_ \ / -_) || | || / _/ -_) | (__ | | 
# |_| \__,_|_|_|_| .__/_\___|\__/ \_,_\__\___|  \___|___|
#                |_|                                     

name: YAML Build and Test

# Recent Change List
# - Strip binary symbols after testing, before codesign (November 1 2024)

# [===================================================================]
# [================ Global Variables Needed By Runner ================]
# [===================================================================]

# For Google Drive upload
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: # lets you run a build from the UI
  #push:
  #pull_request:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release
  BUILD_DIR: Builds
  DISPLAY: :0 # linux pluginval needs this
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_MULTIARCH: 1
  IPP_DIR: C:\Program Files (x86)\Intel\oneAPI\ipp\latest\lib\cmake\ipp
  SHOULD_STRIP_SYMBOLS: false
  TEST_SYMBOL: processBlock
  # Removed USER_TO_IMpersonate since impersonation is handled in authentication

defaults:
  run:
    shell: bash

# [======================================]
# [================ Jobs ================]
# [======================================]

jobs:
  build_and_test:
    # don't double run on PRs
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: macOS
            os: macos-14
            pluginval-binary: pluginval.app/Contents/MacOS/pluginval
            extra-flags: -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
            lameFilename: lame

    steps:

      # [====================================================]
      # [================ Setup Environments ================]
      # [====================================================]

      - name: Set number of cores
        run: |
          echo "Determining number of cores..."
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            CORES=$(nproc)
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            CORES=$(sysctl -n hw.ncpu)
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            CORES=$NUMBER_OF_PROCESSORS
          else
            echo "Unknown OS. Defaulting to 2 cores."
            CORES=2
          fi
          echo "NUMBER_OF_CORES=$CORES" >> $GITHUB_ENV
          echo "Detected $CORES cores"

      - name: Set PRODUCT_NAME and VERSION
        run: |
          echo "PRODUCT_NAME=MyAwesomePlugin" >> $GITHUB_ENV
          echo "VERSION=1.2.3" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Save main repo commit to file (macOS)
        if: ${{ matrix.name == 'macOS' }}
        run: git rev-parse HEAD > main_repo_commit.txt

      - name: Save git submodule output to file
        run: |
          git submodule > git_submodule_versions.txt

      - name: Upload submodule output artifact (macOS)
        if: ${{ matrix.name == 'macOS' }}
        uses: actions/upload-artifact@v4
        with:
          name: git_submodule_versions.txt
          path: git_submodule_versions.txt

      - name: Upload main module output artifact (macOS)
        if: ${{ matrix.name == 'macOS' }}
        uses: actions/upload-artifact@v4
        with:
          name: main_repo_commit.txt
          path: main_repo_commit.txt

      # [========================================================]
      # [================ Authenticate to Google Cloud ============]
      # [========================================================]

      - name: Authenticate and Configure Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_DRIVE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}
          service_account_subject: satbir@sottovocedsp.com
          create_credentials_file: true
          export_environment_variables: true

      # [========================================================]
      # [================ Install Python Dependencies ===========]
      # [========================================================]

      - name: Install Python Dependencies for Drive Upload
        run: |
          python3 -m pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib --break-system-packages

      # [========================================================]
      # [================ Create Python Scripts ==================]
      # [========================================================]

      - name: Create Python Upload Script
        run: |
          cat > upload_to_drive.py <<EOF
          import os
          import sys
          import datetime
          import google.auth
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload
          from google.auth.exceptions import DefaultCredentialsError
          from googleapiclient.errors import HttpError

          # Updated SCOPES for full Drive access and metadata
          SCOPES = [
              'https://www.googleapis.com/auth/drive',
              'https://www.googleapis.com/auth/drive.metadata'
          ]

          def build_service():
              try:
                  creds, project_id = google.auth.default(scopes=SCOPES)
                  service = build('drive', 'v3', credentials=creds)
                  return service
              except DefaultCredentialsError as e:
                  print(f"Failed to obtain default credentials: {e}")
                  sys.exit(1)

          def find_shared_folder(service, name, parent_id=None, owner_email=None, create_if_not_found=False):
              query_parts = [
                  f"name='{name}'",
                  "mimeType='application/vnd.google-apps.folder'",
                  "trashed=false"
              ]
              if parent_id:
                  query_parts.append(f"'{parent_id}' in parents")
              if owner_email:
                  query_parts.append(f"'{owner_email}' in owners")

              query = " and ".join(query_parts)
              try:
                  results = service.files().list(
                      q=query,
                      spaces='drive',
                      fields='files(id, name)',
                      pageSize=1000
                  ).execute()
                  files = results.get('files', [])
              except HttpError as e:
                  print(f"An error occurred while listing folders: {e}")
                  sys.exit(1)

              if not files:
                  if create_if_not_found:
                      print(f"Folder '{name}' not found. Creating it...")
                      folder_metadata = {
                          'name': name,
                          'mimeType': 'application/vnd.google-apps.folder'
                      }
                      if parent_id:
                          folder_metadata['parents'] = [parent_id]
                      try:
                          folder = service.files().create(
                              body=folder_metadata,
                              fields='id'
                          ).execute()
                          print(f"Created folder '{name}' with ID: {folder.get('id')}")
                          return folder.get('id')
                      except HttpError as e:
                          print(f"Failed to create folder '{name}': {e}")
                          sys.exit(1)
                  else:
                      if owner_email:
                          print(f"Error: Could not find folder '{name}' owned by '{owner_email}'.")
                      else:
                          print(f"Error: Could not find folder '{name}'.")
                      sys.exit(1)

              if len(files) > 1:
                  print(f"Warning: Multiple folders named '{name}' found. Using the first one: {files[0]['id']}")

              return files[0]['id']

          def main():
              service = build_service()

              # Use the pre-shared top-level folder "Releases" owned by ROOT_FOLDER_OWNER
              ROOT_FOLDER_NAME = "Releases"
              ROOT_FOLDER_OWNER = "satbir@sottovocedsp.com"
              DRIVE_NEW_OWNER = "satbir@sottovocedsp.com"
              PRODUCT_NAME = os.getenv('PRODUCT_NAME')
              VERSION = os.getenv('VERSION')

              if not PRODUCT_NAME or not VERSION:
                  print("PRODUCT_NAME or VERSION is not set.")
                  sys.exit(1)

              # Find the root 'Releases' folder owned by ROOT_FOLDER_OWNER
              root_folder_id = find_shared_folder(service, ROOT_FOLDER_NAME, owner_email=ROOT_FOLDER_OWNER)

              # Within the root 'Releases' folder, find or create the plugin folder
              plugin_folder_id = find_shared_folder(service, PRODUCT_NAME, parent_id=root_folder_id, create_if_not_found=True)

              # Create a version-specific subfolder within the plugin folder
              now_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d_%H-%M")
              version_folder_name = f"Release_{VERSION}_{now_str}"
              version_folder_id = find_shared_folder(service, version_folder_name, parent_id=plugin_folder_id, create_if_not_found=True)

              # Grant writer access to the user (optional, since we're acting as the user)
              permission_body_writer = {
                  'role': 'writer',
                  'type': 'user',
                  'emailAddress': DRIVE_NEW_OWNER
              }
              try:
                  service.permissions().create(
                      fileId=version_folder_id,
                      body=permission_body_writer,
                      fields='id'
                  ).execute()
                  print(f"Granted writer access to folder '{version_folder_name}' for '{DRIVE_NEW_OWNER}'.")
              except HttpError as error:
                  print(f"An error occurred while granting permissions: {error}")
                  sys.exit(1)

              # Since we're impersonating the user, transferring ownership is unnecessary
              # Files created will be owned by the impersonated user

              # Upload artifacts
              for artifact_path in sys.argv[1:]:
                  if not os.path.exists(artifact_path):
                      print(f"Warning: {artifact_path} does not exist. Skipping.")
                      continue
                  file_name = os.path.basename(artifact_path)
                  media = MediaFileUpload(artifact_path, resumable=True)
                  body = {'name': file_name, 'parents': [version_folder_id]}
                  try:
                      uploaded_file = service.files().create(body=body, media_body=media, fields='id').execute()
                      print(f"Uploaded {artifact_path} to folder {version_folder_id} (ID: {uploaded_file['id']})")
                  except HttpError as error:
                      print(f"Failed to upload {artifact_path}: {error}")
                      continue

              # Set output using environment files
              with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                  fh.write(f"VERSION_FOLDER_ID={version_folder_id}\n")

          if __name__ == "__main__":
              main()
          EOF

      - name: Create Python List Folders Script
        run: |
          cat > list_folders.py <<EOF
          import os
          import sys
          import google.auth
          from googleapiclient.discovery import build
          from google.auth.exceptions import DefaultCredentialsError
          from googleapiclient.errors import HttpError

          SCOPES = ['https://www.googleapis.com/auth/drive.metadata.readonly']

          def build_service():
              try:
                  creds, project_id = google.auth.default(scopes=SCOPES)
                  service = build('drive', 'v3', credentials=creds)
                  return service
              except DefaultCredentialsError as e:
                  print(f"Failed to obtain default credentials: {e}")
                  sys.exit(1)

          def list_all_folders(service):
              query = "mimeType='application/vnd.google-apps.folder' and trashed=false"
              page_token = None
              while True:
                  try:
                      response = service.files().list(
                          q=query,
                          spaces='drive',
                          fields='nextPageToken, files(id, name, owners)',
                          pageToken=page_token
                      ).execute()
                      for folder in response.get('files', []):
                          owners = [owner.get('emailAddress') for owner in folder.get('owners', [])]
                          print(f"Folder Name: {folder.get('name')}, ID: {folder.get('id')}, Owners: {owners}")
                      page_token = response.get('nextPageToken', None)
                      if page_token is None:
                          break
                  except HttpError as e:
                      print(f"An error occurred while listing folders: {e}")
                      sys.exit(1)

          def main():
              service = build_service()
              print("Listing all accessible folders:")
              list_all_folders(service)

          if __name__ == "__main__":
              main()
          EOF

      # [========================================================]
      # [================ List Accessible Folders ================]
      # [========================================================]

      - name: List Accessible Folders
        run: |
          echo "Listing all accessible folders for the impersonated user..."
          python3 list_folders.py > accessible_folders.txt
          cat accessible_folders.txt
          # Optionally, upload the list as an artifact for debugging
          echo "Uploading accessible_folders.txt as an artifact..."
          mkdir -p debug
          mv accessible_folders.txt debug/
          echo "Accessible folders listed above."

      # [========================================================]
      # [================ Upload To Google Drive ================]
      # [========================================================]

      - name: Upload macOS Artifacts to Google Drive
        if: ${{ matrix.name == 'macOS' }}
        run: |
          echo "Uploading macOS artifacts to Google Drive..."
          DMG_PATH="packaging/${{ env.ARTIFACT_NAME }}.dmg"
          SUBMODULE_PATH="git_submodule_versions.txt"
          COMMIT_PATH="main_repo_commit.txt"
          python3 upload_to_drive.py "$DMG_PATH" "$SUBMODULE_PATH" "$COMMIT_PATH"

  # [=========================================]
  # [================ Release ================]
  # [=========================================]

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            *.exe
            *.dmg
            git_submodule_versions.txt
            main_repo_commit.txt
